# Build stage
FROM golang:1.24 AS builder

WORKDIR /app
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o app

# Final stage
FROM debian:bookworm-slim

RUN useradd -m appuser
WORKDIR /app

COPY --from=builder /app/app .

USER appuser

EXPOSE 8000

CMD ["./app"]
